### ISSUE TITLE
Create Todo List.

### ISSUE THREAD

**Issue by seprintour** [Seprintour-Test/test#18]
> Make the todo list

###### [ **[ View Conversation Context ]** ](https://t.me/c/1890045751/31)

**Comment by 0x4007** [comment]
Can you enable assistive pricing

**Comment by seprintour** [comment]
> Can you enable assistive pricing

I'd try and do that now

**Comment by seprintour** [comment]
> Can you enable assistive pricing

The repo does not support time that are not exactly how they are on the config, we talked about it last month when i had the time labels to directly match what we have on the repos and you asked that it be removed in favor of parsing time directly using `ms`
