### ISSUE TITLE
Update Documentation On The Ubiquity Readme

### ISSUE THREAD

**Issue by seprintour** [Seprintour-Test/test#43]
modify the documentation on the ubiquity readme

###### [ **[ View on Telegram ]** ](https://t.me/c/1975484291/223)

**Comment by 0x4007** [comment]
```diff
! Permit generation disabled because label "Priority: 3 (High)" was modified by an unauthorized user
```

Change to that

**Comment by seprintour** [comment]
> ```diff
> ! Error: Column 'bounty_hunter_address' of relation 'permits' does not exist
> ```

This error is because the new permit PR hasn't been merged in, my DB table is already on the new format.. thus the error
