### ISSUE TITLE
Setup Telegram Bot and Map Groups to Repository.

### ISSUE THREAD

**Issue by seprintour** [Seprintour-Test/test#7]
> @pavlovcik I think we have all we need for the bot setup now.
> 
> What's left to do is create an account for Posting Issues or use a personal account (whichever works for the PAT), 
> setup the telegram bot and map groups to their respective repo

https://t.me/c/1738021587/409

**Comment by 0x4007** [comment]
@seprintour I am cautious of including any tagged names unless its used for assign, because we can tag anybody on GitHub but we can only assign contributors. 

I'm unsure if we should leave it as is (seems to make sense) or scrub any tags so that the bot doesn't get marked as spam, for example. 

> create an account for Posting Issues

No this should auth as UbiquiBot. We've already implemented CI that authorizes as the bot to post a comment so I know its definitely doable!

For example, check the deploys we have on `ubiquity-dollar`
1. https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/workflows/continuous-deploy.yml
2. https://github.com/ubiquity/.github/blob/main/.github/workflows/deploy.yml
3. https://github.com/ubiquity/ubiquity-dollar/pull/751#issuecomment-1672157197

> map groups to their respective repo

Can you elaborate?

**Comment by seprintour** [comment]
> No this should auth as UbiquiBot. We've already implemented CI that authorizes as the bot to post a comment so I know its definitely doable!

I've tried it on the cloudflare worker and it does not work.. soemhow even when i enable nodejs support.. most things break

So maybe what'd do is create a CI that gets the `installation_token` then we'd pass that to the cloudlfare worker secret for use

**Comment by seprintour** [comment]
> Can you elaborate?

I mean every group would have a corresponding repo here: https://github.com/ubiquity/telegram-ubiquibot/blob/f54351b5ef9a6da91c542fda79acd06948c0a039/src/constants.js#L3C4-L3C4

So we'd have to set that up

**Comment by seprintour** [comment]
> I'm unsure if we should leave it as is (seems to make sense) or scrub any tags so that the bot doesn't get marked as spam, for example.
> 
> >
 
 Yea, i just removed tags on github issue body

**Comment by 0x4007** [comment]
> I mean every group would have a corresponding repo here: https://github.com/ubiquity/telegram-ubiquibot/blob/f54351b5ef9a6da91c542fda79acd06948c0a039/src/constants.js#L3C4-L3C4

Oh I see so this is a temporary solution. Sure. 

> Yea, i just removed tags on github issue body

Be sure to `trim()` the body so that spaces in the beginning or end are trimmed off as those are common places to tag somebody (assuming you are just removing the tag and not handling the spaces around it.)

**Comment by 0x4007** [comment]
###### [ **[ View Conversation Context ]** ](https://t.me/c/1738021587/409)

```
###### [ **[ View Conversation Context ]** ](https://t.me/c/1738021587/409)
```

Use this for the Telegram link.

**Comment by 0x4007** [comment]
> I've tried it on the cloudflare worker and it does not work.. soemhow even when i enable nodejs support.. most things break

It depends on secrets only available inside of repositories inside of our organization.

**Comment by seprintour** [comment]
> It depends on secrets only available inside of repositories inside of our organization.

I meant using of private key requires JWT (a nodejs module) and cloudflare workers do not fully support it yet so it does not work

For this to work, i'd have to write a CI that'd get the token and then automatically add the env then deploy

**Comment by 0x4007** [comment]
> For this to work, i'd have to write a CI that'd get the token and then automatically add the env then deploy

Perhaps a new bounty then.

**Comment by pavlovcik** [comment]
How about automatic pricing? Is that not possible currently?

**Comment by 0x4007** [comment]
@seprintour I'm about to finish work for today. What is the status? What are next steps?

**Comment by seprintour** [comment]
> @seprintour I'm about to finish work for today. What is the status? What are next steps?

I was busy on the CI script so it'd be easy to deploy and set up.. its the only thing left now

**Comment by seprintour** [comment]
One problem we have with this implementation is [This line](https://github.com/seprintour/telegram-ubiquibot/blob/5217ef00f866a3a1879f799ae2cdc5d24d74e89a/.github/workflows/cloudflare-deploy.yml#L31) 

It gets the installation token and i can use it to authenticate the bot action but for this repo only, it cannot work for any other repo so we'd need to get the installation_token of all the other repo manually so that the bot would be able to post issues on em

I think we should make use of a personal account specifically for the telegram bot for now and take out time to setup how we are going to use the installation token

**Comment by seprintour** [comment]
Successful here: https://github.com/seprintour/telegram-ubiquibot/actions/runs/5816854203/job/15770591773

And i have tested it to create an issue here: https://github.com/Seprintour-Test/test/issues/8

Looks like the `ubiquibot-qa` does not have access to add labels and assignee, so you see the limitations and why an account meant for this might be a good idea

**Comment by seprintour** [comment]
Okay, i was able to make it work.. Tested [here](https://github.com/ubiquity/telegram-ubiquibot/issues/5) (Please delete)

Looks like we have to make a new bot for it or give this ability to create labels and add assignees on the repo we need it to post

**Comment by seprintour** [comment]
<img width="820" alt="Screenshot 2023-08-10 at 5 31 14 AM" src="https://github.com/Seprintour-Test/test/assets/51956013/4c1985f7-8b55-4df0-a686-daf483bfb4f9">

It also does not have access to see the members of an org

**Comment by 0x4007** [comment]
> <img width="820" alt="Screenshot 2023-08-10 at 5 31 14 AM" src="https://github.com/Seprintour-Test/test/assets/51956013/4c1985f7-8b55-4df0-a686-daf483bfb4f9">
> 
> 
> 
> It also does not have access to see the members of an org

Is this required for assignment? I can add it. I just need to know why it's needed first.

**Comment by seprintour** [comment]
> > <img alt="Screenshot 2023-08-10 at 5 31 14 AM" width="820" src="https://user-images.githubusercontent.com/51956013/259622491-4c1985f7-8b55-4df0-a686-daf483bfb4f9.png">
> > It also does not have access to see the members of an org
> 
> Is this required for assignment? I can add it. I just need to know why it's needed first.

To get collaborators in the organization and then assign them if they are tagged

**Comment by 0x4007** [comment]
<img width="792" alt="image" src="https://github.com/Seprintour-Test/test/assets/4975670/9724b776-34d9-46f2-a569-af7e4edb8c3f">

Production bot has this capability, which I believe is what should be invoked from the secrets. 

> Okay, i was able to make it work.. Tested https://github.com/ubiquity/telegram-ubiquibot/issues/5 (Please delete)

Technically the UbiquiBot[QA] instance belongs to the @ubiquibot organization, and not the @ubiquity organization. It is sandboxed for security reasons. That's most likely why it can't assign etc. It is not added to the @ubiquity organization.
